import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/views/Header";
import Wrapper from "@/components/ui/Wrapper";
import Catagory from "@/components/ui/Catagory";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Wrapper>
            <Header />
            {children}
            <Toaster />
          </Wrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
